Personalpages
Prains/sansearch pull request #15
Opened 2023-05-17 13:04 UTC by PchelaMaya

2023-05-17 15:19 UTC, Prains commented on components/PersonalPages/PersonalDataAndSubscription/PersonalData/FormProfile/FormProfile.jsx
> +                <input
хардкод. ты повторяешь один и тот же компонент. вынеси его в отдельный компонент и пройдись по массиву

2023-05-17 15:19 UTC, Prains commented on components/PersonalPages/PersonalDataAndSubscription/PersonalData/FormProfile/FormProfile.jsx
> +                <label className="text-[22px] lg:inline-block lg:w-[120px]">{labelInput[4]}</label>
неправильно используешь label.https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2023-05-17 15:20 UTC, Prains commented on components/PersonalPages/PersonalDataAndSubscription/PersonalSubscription/PersonalSubscription.jsx
> +const PersonalSubscription = () => {
код невозможно запустить в локальной среде. посмотри, что за ошибка и исправь ее

2023-05-17 17:29 UTC, PchelaMaya commented on components/PersonalPages/PersonalDataAndSubscription/PersonalSubscription/PersonalSubscription.jsx
> +const PersonalSubscription = () => {
у меня всё запускается

2023-05-17 22:42 UTC, Prains commented on components/PersonalPages/PersonalDataAndSubscription/PersonalSubscription/PersonalSubscription.jsx
> +const PersonalSubscription = () => {
SyntaxError: Unexpected token < in JSON at position 427
    at JSON.parse (<anonymous>)
    at patchIncorrectLockfile (D:\Desktop\sansearch\node_modules\next\dist\lib\patch-incorrect-lockfile.js:93:33)

2023-05-19 09:46 UTC, Prains requested changes
удали инпуты фамилия и компания. пароль и новый пароль появляется только когда человек нажимает кнопку изменить данные. данные о пользователе получай из слайса user в redux. если данных о пользователе нет, переводи пользователя на раут /

2023-05-19 10:34 UTC, merged